name: Build

on:
  push:
    branches:
      - 'production'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: touch .env
      - run: npm run build
        env:
          CI: true
        name: Publish (deploy)
      - run: echo ${{ secrets.DEPLOYMENT_SSH_KEY }} >> key.rsa
      - run: chmod 600
      - run: scp -i key.rsa ./build/* github@polygloat.io:/data/polygloat/deployment_test/
      - run: rm key.rsa