name: Deploy

on:
  push:
    branches:
      - 'production'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: touch .env
      - run: npm run build
        env:
          CI: true
      - uses: nogsantos/scp-deploy@master
        name: Publish (deploy)
        with:
          host: polygloat.io
          user: github
          port: 22
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          src: "./build/*"
          remote: "/data/polygloat/website"