name: Build

on:
  push:
    branches:
      - 'production'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: touch .env
      - run: npm run build
        env:
          CI: true
      - uses: appleboy/scp-action@master
        with:
          host: polygloat.io
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          source: "build/*"
          target: "/data/polygloat/deployment_test/"